# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.define "centos-vanilla_dockerhost"
  config.vm.box_download_insecure = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    curl https://raw.githubusercontent.com/popebob/learn-bash/develop/install-docker/scripts/install-docker-on-centos7.sh > install-docker-on-centos7.sh
    chmod +x install-docker-on-centos7.sh
    sudo ./install-docker-on-centos7.sh -install
    curl https://raw.githubusercontent.com/popebob/learn-bash/develop/install-docker/scripts/add-docker-compose.sh > add-docker-compose.sh
    chmod +x add-docker-compose.sh
    sudo ./add-docker-compose.sh -install
  SHELL
end
