# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3-pip
    sudo apt update
    sudo apt install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
    ansible-galaxy install angstwad.docker_ubuntu
    ansible-galaxy install 'git+https://github.com/TerryHowe/ansible-modules-hashivault.git'
    git config --global credential.helper store
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az account show
  SHELL
end
