# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt update
    sudo apt install -y jq
    sudo apt install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
    # the carriage returns and strange alignment in the next line are needed for the tee command at the nd
    echo "# Use the YAML callback plugin.
stdout_callback = yaml
# Use the stdout_callback when running ad-hoc commands.
bin_ansible_callbacks = True" | sudo tee -a /etc/ansible/ansible.cfg
    ansible-galaxy install angstwad.docker_ubuntu
    ansible-galaxy install 'git+https://github.com/TerryHowe/ansible-modules-hashivault.git'
    export ANSIBLE_HOST_KEY_CHECKING=False
    git config --global credential.helper store
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az account show
    sudo apt install -y python3-pip
    pip3 install termcolor
    pip3 install pyhcl
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install terraform=0.13.0
    sudo apt-get update && sudo apt-get install nomad=0.12.9
  SHELL
end
